version: '3.10'

services:
  nginx:
    image: nginx:1.25.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/getting_ssl/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - template_value:/var/html/template/
      - ./deploy/certbot/www/:/var/www/certbot/:ro
      - ./deploy/certbot/conf/:/etc/nginx/ssl/:ro
    environment:
      HOSTNAME: ${DOMAIN_NAME}
    restart: always

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email ${EMAIL} --agree-tos --no-eff-email --staging -d ${DOMAIN_NAME}
    volumes:
      - ./deploy/certbot/www/:/var/www/certbot/:rw
      - ./deploy/certbot/conf/:/etc/letsencrypt/:rw
