version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s\t%(levelname)s\t%(filename)s:%(lineno)d\t%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "filename": "%(filename)s", "lineno": %(lineno)d, "message": "%(message)s"}'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

loggers:
  app:
    level: INFO
    handlers: [console_handler]
    propagate: yes

  fastapi:
    level: INFO
    handlers: [console_handler]
    propagate: yes

  aiogram.event:
    level: WARNING
    handlers: [console_handler]
    propagate: no

  sqlalchemy:
    level: WARNING
    handlers: [console_handler]
    propagate: yes

  sqlalchemy.engine:
    level: WARNING
    handlers: [console_handler]
    propagate: no

  sqlalchemy.orm:
    level: WARNING
    handlers: [console_handler]
    propagate: no

  apscheduler:
    level: INFO
    handlers: [console_handler]
    propagate: yes

  redis:
    level: WARNING
    handlers: [console_handler]
    propagate: yes

  asyncio:
    level: WARNING
    handlers: [console_handler]
    propagate: yes

  asyncpg:
    level: WARNING
    handlers: [console_handler]
    propagate: no

  uvicorn:
    level: INFO
    handlers: [console_handler]
    propagate: no

  uvicorn.error:
    level: ERROR
    handlers: [console_handler]
    propagate: no

  uvicorn.access:
    level: WARNING
    handlers: [console_handler]
    propagate: no
