version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s\t%(levelname)s\t%(filename)s:%(lineno)d\t%(message)s"
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "filename": "%(filename)s", "lineno": %(lineno)d, "message": "%(message)s"}'

handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  timed_rotating_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: json
    filename: log.file
    backupCount: 14
    encoding: utf-8
    when: midnight
    interval: 1

loggers:
  app:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no
  fastapi:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no
  aiogram.event:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no
  sqlalchemy:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no
  sqlalchemy.engine:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no
  sqlalchemy.orm:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no
  apscheduler:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no
  redis:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no
  asyncio:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no
  asyncpg:
    level: INFO
    handlers: [console_handler, timed_rotating_handler]
    propagate: no