name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 5432:5432
          - 6379:6379
          - 80:80
          - 443:443
          - 8000:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: docker-compose build

      - name: Run Docker Compose
        uses: docker/compose-action@v2
        with:
          compose-file: ./docker-compose.yml
          up-flags: --build -d

      - name: Run tests
        run: docker-compose exec backend pytest

      - name: Tear down Docker Compose
        run: docker-compose down
