name: CI/CD Pipeline

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: docker-compose build

      - name: Deploy to remote server
        run: |
          scp -r ./* user@${{ secrets.SSH_HOST }}:/path/to/deploy
          ssh user@${{ secrets.SSH_HOST }} 'cd /path/to/deploy && docker-compose up -d --build'

      - name: Run tests
        run: docker-compose exec backend pytest

      - name: Tear down Docker Compose
        run: docker-compose down
